---
# Install the library files that php54 depends on
# 2018-04-08 19:53 by liubaobao at WDTY company


- name: Install Packages Needed To Compile PHP 54
  apt: name={{ item }} state=latest
  with_items:
    - autoconf
    - libpcre3-dev
    - libssl-dev
    - libxml2-dev
    - libcurl4-openssl-dev
    - libbz2-dev
    - libjpeg8-dev
    - libpng++-dev
    - libfreetype6-dev
    - libmcrypt-dev
    - libmemcached-dev
    - libgearman-dev
    - libmagickwand-dev
    - libmagickcore-dev
    - libevent-dev
  tags: compile

- name: Configure the build Freetype
  command: ./configure
  args:
    chdir: /tmp/{{ FREETYPE }}/

- name: Build compile freetype
  command: make -j
  args:
    chdir: /tmp/{{ FREETYPE }}/

- name: Install freetype
  command: make install
  args:
    chdir: /tmp/{{ FREETYPE }}/
