---
#Install imagick extension for php
##2018-04-06 12:07 by liubaobao at WDTY company


- name: Load imagick extend
  command: /home/yx/server/php54/bin/phpize
  args:
    chdir: /tmp/{{ IMAGICK }}/

- name: Configure the build
  command: ./configure {{ PHPCOMCONFiGURE }}
  args:
    chdir: /tmp/{{ IMAGICK }}/

- name: Build imagick extend
  command: make -j
  args:
    chdir: /tmp/{{ IMAGICK }}/

- name: Install imagick extend
  command: make install
  args:
    chdir: /tmp/{{ IMAGICK }}/
