#Install zendopcache extension for php
##2018-04-06 12:07 by liubaobao at WDTY company


- name: Load zendopcache extend
  command: /home/yx/server/php54/bin/phpize
  args:
    chdir: /tmp/{{ ZENDOPCACHE }}/

- name: Configure the build
  command: ./configure {{ PHPCOMCONFiGURE }}
  args:
    chdir: /tmp/{{ ZENDOPCACHE }}/

- name: Build zendopcache extend
  command: make -j
  args:
    chdir: /tmp/{{ ZENDOPCACHE }}/

- name: Install zendopcache extend
  command: make install
  args:
    chdir: /tmp/{{ ZENDOPCACHE }}/
