#Sync php related config file
#2018-04-08 22:44 by liubaobao at WDTY company
---
- name: Sync php-fpm config
  copy: src={{ PHPFPMCONF }} dest=/home/yx/server/php54/etc/{{ PHPFPMCONF }} backup=yes owner=yx group=yx mode=0644
  ignore_errors: True
  tags: php-fpmconf

- name: Sync php script
  copy: src={{ PHPSH }} dest=/home/yx/server/php54/{{ PHPSH }} backup=yes owner=yx group=yx mode=0644
  ignore_errors: True
  tags: phpscript

- name: Sync php config
  copy: src={{ PHPCONF }} dest=/home/yx/server/php54/lib/{{ PHPCONF }} backup=yes owner=yx group=yx mode=0644
  ignore_errors: True
  tags: phpconf
